apiVersion: v1
kind: Pod
metadata:
name: git-sync
labels:
app: sidecar
spec:
containers:
- name: ctr-web <<==== First container (main app)
image: nginx
volumeMounts:
- name: html <<==== Mount shared volume
mountPath: /usr/share/nginx/
- name: ctr-sync <<==== Second container (sidecar)
image: k8s.gcr.io/git-sync:v3.1.6
volumeMounts:
- name: html <<==== Mount shared volume
mountPath: /tmp/git
env:
- name: GIT_SYNC_REPO
value: https://github.com/nigelpoulton/ps-sidecar.git
- name: GIT_SYNC_BRANCH
value: master
- name: GIT_SYNC_DEPTH
value: "1"
- name: GIT_SYNC_DEST
value: "html"
volumes:
- name: html <<==== Shared volume
emptyDir: {}
